// <auto-generated />
using Integration.Data;
using Integration.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Integration.Migrations
{
    [DbContext(typeof(EmployeeDBContext))]
    [Migration("20180711111323_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Integration.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LangKnown");

                    b.Property<string>("address");

                    b.Property<string>("email");

                    b.Property<string>("experience");

                    b.Property<string>("firstname");

                    b.Property<string>("gender");

                    b.Property<string>("lastname");

                    b.Property<string>("password");

                    b.Property<string>("qualification");

                    b.Property<string>("username");

                    b.HasKey("id");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
